In [1]:
import torch

In [2]:
print(torch.__version__)

2.1.0+cu121


In [ ]:
#The tensors are created using the torch.tensor()

In [3]:
scalar=torch.tensor(9)
scalar

tensor(9)

In [ ]:
# to get the tensor back as a integer of python

In [4]:
scalar.item()

9

In [6]:
# number of dimensions
scalar.ndim

0

In [7]:
# shape
scalar.shape

torch.Size([])

In [8]:
vector=torch.tensor([1,2])
vector

tensor([1, 2])

In [11]:
# lets check shape and dimenions of the vector
vector.shape

torch.Size([2])

vector.ndim

In [ ]:
 # now we try to build a matrix, check its shape and dimentions and try to access them

In [14]:
m=torch.tensor([[1,2],[3,4]])
m

tensor([[1, 2],
        [3, 4]])

In [15]:
m.shape

torch.Size([2, 2])

In [16]:
m.ndim

2

In [ ]:
# as we know that we can compute millions of numerical data using pytorch lets increase the difficulty and try to understand better about the shapes and dimensions

In [17]:
mat=torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
mat

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
mat.ndim

3

In [20]:
mat.shape

torch.Size([1, 3, 3])

In [ ]:
# in the previous case we have seen that the dimention is [2,2] but now it shows [1,3,3]. It is a bit difficult to understand.
# in the above dimension values the 1 represents the outer most square bracket and 3 represents the next and the next 3 represents the next

In [ ]:
# lets try indexing

In [21]:
mat[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
matt=torch.tensor([[[[1,2],
                     [3,4],
                     [5,6],
                     [7,8]]]])
matt

tensor([[[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]])

In [26]:
matt.ndim

4

In [27]:
# I think with this example we can better understand the dimensions of the tensors
matt.shape


torch.Size([1, 1, 4, 2])

# lets create a tensor with random values


In [29]:
r=torch.rand(2,3)
r

tensor([[0.8779, 0.2647, 0.7646],
        [0.3751, 0.2837, 0.1231]])

In [30]:
re=torch.rand(5,5,5)
re

tensor([[[0.6503, 0.4471, 0.4786, 0.0586, 0.1569],
         [0.7632, 0.2948, 0.4343, 0.6423, 0.8872],
         [0.8164, 0.1757, 0.4596, 0.8784, 0.4572],
         [0.7151, 0.5349, 0.4325, 0.3502, 0.1688],
         [0.7799, 0.4776, 0.0845, 0.3193, 0.6351]],

        [[0.0020, 0.8581, 0.6925, 0.2964, 0.7564],
         [0.4778, 0.0783, 0.3955, 0.7766, 0.5854],
         [0.8535, 0.4614, 0.7852, 0.1051, 0.1260],
         [0.1220, 0.8365, 0.0791, 0.3042, 0.2480],
         [0.4538, 0.0578, 0.0842, 0.0775, 0.5636]],

        [[0.0162, 0.2555, 0.4834, 0.5958, 0.0624],
         [0.9422, 0.7187, 0.3963, 0.6484, 0.8808],
         [0.0114, 0.6649, 0.9366, 0.9112, 0.1000],
         [0.3610, 0.3838, 0.8750, 0.8483, 0.5525],
         [0.4968, 0.0493, 0.1856, 0.9247, 0.3100]],

        [[0.4801, 0.0251, 0.3396, 0.3910, 0.6920],
         [0.6260, 0.8422, 0.2120, 0.3793, 0.9392],
         [0.6342, 0.7507, 0.6927, 0.8682, 0.9529],
         [0.5469, 0.4539, 0.0848, 0.7823, 0.2714],
         [0.3054, 0.0691,

In [31]:
re.shape

torch.Size([5, 5, 5])

In [34]:
# the default data type for random tensor is float32
re.dtype

torch.float32

# what is the use of random tensors??
# The first step of neural networks is to generate the random numbers then look at the data and then they update the values again and again

# lets create the tensors with only zeroes and ones

In [33]:
z=torch.zeros(size=(4,4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
o=torch.ones(7,3)
o

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [37]:
# lets check the default data types
z.dtype
o.dtype

torch.float32

# Create a tensor with a range

In [39]:
x=torch.range(1,10)
x

<ipython-input-39-67fdbf106b23>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x=torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
x=torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# as we can see the older version of range is deprecated and replaced with a new arange
# not only the above way we can print tensors with step differnce between them

In [42]:
x=torch.arange(start=0, end=100, step=5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [ ]:
# as we can observe the end is not included.