In [ ]:
import torch

### lets try to change the datatype of tensor

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
# the deafult datatype is float32
tensor_16 = tensor.type(torch.float16)
tensor_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Look at the following

1. Reshaping - this helps to change the shape or dimensions without changing the values

2. Stacking - this helps in concatenating a sequence of tensors

3. View - this helps in seeing a view of tensor

4. Squeezing - this helps in removing dimensions with value 1

5. Unsqueezing - this helps in adding dimension with value 1

6. Permute - returns a view with reshaped dimensions

In [ ]:
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped

RuntimeError: shape '[1, 7]' is invalid for input of size 12

In [ ]:
x_reshaped = x.reshape(3, 4)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
x_reshaped = x.reshape(4, 3)
x_reshaped

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
x_reshaped = x.reshape(12, 1)
x_reshaped

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])

In [ ]:
z = x.view(1, 12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [ ]:
# the change in z also changes the x also
# as z is stored in same memory location as x

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [ ]:
## lets change the dimensions and check it

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [ ]:
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


New tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
New shape: torch.Size([12])


In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
New shape: torch.Size([1, 12])


In [ ]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing

In [ ]:
x = torch.arange(1, 13).reshape(1, 4, 3)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
x.shape

torch.Size([1, 4, 3])

lets try to index bracket by bracket

In [ ]:
x[0]


tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[ 2,  5,  8, 11]])

### PyTorch tensors & NumPy

In [ ]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0, 13.0)
tensor = torch.from_numpy(array)

In [ ]:
array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       dtype=torch.float64)

In [ ]:
# important point to make a note of is the dtype is float64 but for tensors it will be float32
# if we convert to torch tensor it becomes float32

In [ ]:
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(11)
numpy_tensor = tensor.numpy()

In [ ]:
tensor

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
# now the datatype is float32

### Reproducibility

In [ ]:
random_tensor_A = torch.rand(6, 4)
random_tensor_B = torch.rand(6, 4)


In [ ]:
random_tensor_A

tensor([[0.7440, 0.3998, 0.9748, 0.3237],
        [0.4308, 0.1168, 0.3899, 0.3918],
        [0.9738, 0.3786, 0.2063, 0.8431],
        [0.9270, 0.9296, 0.0040, 0.9791],
        [0.4613, 0.5911, 0.1657, 0.2544],
        [0.6994, 0.2259, 0.9632, 0.6046]])

In [ ]:
random_tensor_B

tensor([[0.6922, 0.6282, 0.0576, 0.4159],
        [0.4651, 0.1307, 0.5383, 0.0054],
        [0.6734, 0.7521, 0.4313, 0.7664],
        [0.0412, 0.3357, 0.7584, 0.8603],
        [0.9666, 0.8190, 0.9947, 0.0422],
        [0.2895, 0.9247, 0.3820, 0.3384]])

In [ ]:
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


*   as we observed the tensors contain random values
*   can we print two tensors with same random values???
*   Yes, its possible
*   Lets check it out



In [ ]:
import random

In [ ]:
# # Set the random seed
RANDOM_SEED=102 # any random number can be set
torch.manual_seed(seed=RANDOM_SEED)

random_tensor_C = torch.rand(6, 4)
random_tensor_D = torch.rand(6, 4)

In [ ]:
random_tensor_C

tensor([[0.0065, 0.7747, 0.0526, 0.4259],
        [0.6161, 0.4129, 0.0695, 0.3166],
        [0.1573, 0.1105, 0.1085, 0.2560],
        [0.8156, 0.9961, 0.9091, 0.1899],
        [0.6305, 0.0115, 0.8873, 0.2573],
        [0.4907, 0.6619, 0.9689, 0.2356]])

In [ ]:
random_tensor_D

tensor([[0.6971, 0.2080, 0.4575, 0.4372],
        [0.5114, 0.1523, 0.3624, 0.0237],
        [0.8513, 0.3691, 0.9748, 0.1571],
        [0.5176, 0.7938, 0.3388, 0.4807],
        [0.2243, 0.9599, 0.5222, 0.0905],
        [0.3104, 0.5823, 0.2259, 0.8686]])

In [ ]:
random_tensor_C==random_tensor_D

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

even now its not same as we wanted because this line "torch.manual_seed(seed=RANDOM_SEED)" should be written before every random tensor lines

In [ ]:
# # Set the random seed
RANDOM_SEED=102 # any random number can be set
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(6, 4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(6, 4)

In [ ]:
random_tensor_C

tensor([[0.0065, 0.7747, 0.0526, 0.4259],
        [0.6161, 0.4129, 0.0695, 0.3166],
        [0.1573, 0.1105, 0.1085, 0.2560],
        [0.8156, 0.9961, 0.9091, 0.1899],
        [0.6305, 0.0115, 0.8873, 0.2573],
        [0.4907, 0.6619, 0.9689, 0.2356]])

In [ ]:
random_tensor_D

tensor([[0.0065, 0.7747, 0.0526, 0.4259],
        [0.6161, 0.4129, 0.0695, 0.3166],
        [0.1573, 0.1105, 0.1085, 0.2560],
        [0.8156, 0.9961, 0.9091, 0.1899],
        [0.6305, 0.0115, 0.8873, 0.2573],
        [0.4907, 0.6619, 0.9689, 0.2356]])

In [ ]:
random_tensor_C==random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])