### Day 2 of Pytorch

In [ ]:
import torch

In [ ]:
s=torch.tensor(3)
s

tensor(3)

In [ ]:
v=torch.tensor([2,3])
v

tensor([2, 3])

In [ ]:
s+v

tensor([5, 6])

In [ ]:
m=torch.tensor([[1,2,3],[4,5,6]])
ms=torch.tensor([3])
s

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
s+v+m

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

we observed some errors while adding a scalar , vector and a matrix
now lets change the dimensions and check it out

In [ ]:
x=torch.tensor([1,2,3])
x+s+m

tensor([[ 5,  7,  9],
        [ 8, 10, 12]])

In [ ]:
t = torch.tensor([3.,4.,5.,6.,7.],
                               dtype=None)



t.shape, t.dtype

(torch.Size([5]), torch.float32)

###now lets find the arrtibutes of a tensor

1.shape
2.data type
3.device

In [ ]:
# Create a tensor
some_tensor = torch.rand(5, 4)

print(some_tensor)
print(f"Shape {some_tensor.shape}")
print(f"Datatype  {some_tensor.dtype}") # the default value is float32
print(f"Device  {some_tensor.device}") # the default device is cpu

tensor([[0.4930, 0.5545, 0.4833, 0.3670],
        [0.1321, 0.7851, 0.2461, 0.1614],
        [0.4362, 0.5454, 0.3155, 0.7643],
        [0.3020, 0.8962, 0.1579, 0.0571],
        [0.7859, 0.7003, 0.4764, 0.8074]])
Shape torch.Size([5, 4])
Datatype  torch.float32
Device  cpu


### tensor operations



1.   Addition
2.   Subtraction
3.   Division
4.   Multiplication(can be performed in two ways)



In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
# Multiply it by 100
tensor * 100

tensor([100, 200, 300])

In [ ]:
# Subtract
tensor = tensor - 100
tensor

tensor([-99, -98, -97])

In [ ]:
tensor / 100 # division

tensor([-0.9900, -0.9800, -0.9700])

### Multiplication

we can use inbuilt funtions for multiplication like multiply

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

In [ ]:
print(tensor, "*", tensor)
print(tensor * tensor)

tensor([-99, -98, -97]) * tensor([-99, -98, -97])
tensor([9801, 9604, 9409])


In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([9801, 9604, 9409])

We can use "matmul" or "@" or "mm" for matrix multiplication

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(28814)

In [ ]:
tensor @ tensor

tensor(28814)

In [ ]:
%%time
# Matrix multiplication
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.36 ms, sys: 30 µs, total: 1.39 ms
Wall time: 1.34 ms


tensor(28814)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 663 µs, sys: 79 µs, total: 742 µs
Wall time: 625 µs


tensor(28814)

From the above two lines of code we can understand that matrix multiplicaton is quiet easy and takes less time using the "mm" or "@" or "matmul" than calculating it by traditional method

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### Rules for matrix multiplication

The above code gives a error as it shows issues with the dimensions.

1. The inner dimensions of the  matrices should match
     example:
            (2,3) @ (3,2) => it works
            (3,2) @ (3,2) => it won't work
2. The resulting matrix will have the shape of outer dimensions:
     example:
            (2,3) @ (3,2) => (2,2)
            (3,2) @ (2,3) => (3,3)


In [ ]:
print(tensor_A)
print(tensor_B.T) # transpose of B

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Tensor Aggregayions

1. Minimum
2. Maximum
3. Mean
4. Sum

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
x.sum()

tensor(450)

In [ ]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

### position of min and max

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
tensor

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.argmin(tensor)

tensor(0)

In [ ]:
torch.argmax(tensor)

tensor(8)

In [ ]:
tensor.argmin()

tensor(0)

In [ ]:
tensor.argmax()

tensor(8)